# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='type',
            field=models.CharField(choices=[('post', 'Post'), ('page', 'Page')], default='post', max_length=10),
        ),
    ]
